// Code generated by "stringer -type=Fu"; DO NOT EDIT.

package yaku

import "strconv"

const _Fu_name = "FuBaseFuBaseClosedRonFuBase7FuSetFuTsumoFuOtherFuNoOpenFuFuBadWaitFuPair"

var _Fu_index = [...]uint8{0, 6, 21, 28, 33, 40, 47, 57, 66, 72}

func (i Fu) String() string {
	if i < 0 || i >= Fu(len(_Fu_index)-1) {
		return "Fu(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Fu_name[_Fu_index[i]:_Fu_index[i+1]]
}
