// Code generated by "stringer -type=Yakuman"; DO NOT EDIT.

package yaku

import "strconv"

const _Yakuman_name = "YakumanKokushiYakumanKokushi13YakumanSuukantsuYakumanSuuankouYakumanSuuankouTankiYakumanDaisangenYakumanShousuushiYakumanDaisuushiYakumanRyuuiisouYakumanTsuiisouYakumanChinroutoYakumanChuurenpootoYakumanChuurenpooto9YakumanTenhouYakumanChihouYakumanRenhou"

var _Yakuman_index = [...]uint8{0, 14, 30, 46, 61, 81, 97, 114, 130, 146, 161, 177, 196, 216, 229, 242, 255}

func (i Yakuman) String() string {
	if i < 0 || i >= Yakuman(len(_Yakuman_index)-1) {
		return "Yakuman(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Yakuman_name[_Yakuman_index[i]:_Yakuman_index[i+1]]
}
