// Code generated by "stringer -type=Yaku"; DO NOT EDIT.

package yaku

import "strconv"

const _Yaku_name = "YakuNoneYakuRiichiYakuDaburiYakuIppatsuYakuTsumoYakuTanyaoYakuChantaYakuJunchanYakuHonroutoYakuYakuhaiYakuHakuYakuHatsuYakuChunYakuWindRoundYakuWindSelfYakuTonYakuNanYakuSjaYakuPeiYakuTonSelfYakuNanSelfYakuSjaSelfYakuPeiSelfYakuTonRoundYakuNanRoundYakuSjaRoundYakuPeiRoundYakuChiitoiYakuToitoiYakuSanankouYakuSankantsuYakuSanshokuYakuShousangenYakuPinfuYakuIppeikoYakuRyanpeikouYakuItsuuYakuSanshokuDoukouYakuHonitsuYakuChinitsuYakuDoraYakuUraDoraYakuAkaDoraYakuRenhouYakuHaiteiYakuHouteiYakuRinshanYakuChankan"

var _Yaku_index = [...]uint16{0, 8, 18, 28, 39, 48, 58, 68, 79, 91, 102, 110, 119, 127, 140, 152, 159, 166, 173, 180, 191, 202, 213, 224, 236, 248, 260, 272, 283, 293, 305, 318, 330, 344, 353, 364, 378, 387, 405, 416, 428, 436, 447, 458, 468, 478, 488, 499, 510}

func (i Yaku) String() string {
	if i < 0 || i >= Yaku(len(_Yaku_index)-1) {
		return "Yaku(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Yaku_name[_Yaku_index[i]:_Yaku_index[i+1]]
}
