// Code generated by "stringer -type=Yakuman"; DO NOT EDIT.

package yaku

import "strconv"

const _Yakuman_name = "YakumanNoneYakumanKokushiYakumanKokushi13YakumanSuukantsuYakumanSuuankouYakumanSuuankouTankiYakumanDaisangenYakumanShousuushiYakumanDaisuushiYakumanRyuuiisouYakumanTsuiisouYakumanChinroutoYakumanChuurenpootoYakumanChuurenpooto9YakumanTenhouYakumanChihouYakumanRenhou"

var _Yakuman_index = [...]uint16{0, 11, 25, 41, 57, 72, 92, 108, 125, 141, 157, 172, 188, 207, 227, 240, 253, 266}

func (i Yakuman) String() string {
	if i < 0 || i >= Yakuman(len(_Yakuman_index)-1) {
		return "Yakuman(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Yakuman_name[_Yakuman_index[i]:_Yakuman_index[i+1]]
}
