// Code generated by "stringer -type=Opponent"; DO NOT EDIT.

package base

import "strconv"

const _Opponent_name = "SelfRightFrontLeft"

var _Opponent_index = [...]uint8{0, 4, 9, 14, 18}

func (i Opponent) String() string {
	if i < 0 || i >= Opponent(len(_Opponent_index)-1) {
		return "Opponent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opponent_name[_Opponent_index[i]:_Opponent_index[i+1]]
}
