name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22.6
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.6

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
            GOPROXY: "off"
        run: make generate build

      - name: Test
        env:
            GOPROXY: "off"
        run: make testcover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: false
