name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24.3
        uses: actions/setup-go@v1
        with:
          go-version: 1.24.3

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "off"
        run: make build

      - name: Test
        env:
          GOPROXY: "off"
        run: make testcover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage.txt
          flags: unittests # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: false # optional (default = false)

